extends Node2D

const TOWER_ID_TO_DESCRPTION_TEXT: Dictionary[TowerConstants.TowerIDs, String]  = {
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_1: "Fires bullet towards creep.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_2: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will ricochet in a random direction.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_3: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will travel towards other another\ncreep in range (if one exists).",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_4: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will ricochet in a random direction.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_5: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will travel towards other another\ncreep in range (if one exists).",
    TowerConstants.TowerIDs.BISMUTH_LVL_1: "Launches homing missile towards target.",
    TowerConstants.TowerIDs.BISMUTH_LVL_2: "Launches homing missile towards target.\nMissile has 15% chance of 0.5 seconds stun.",
    TowerConstants.TowerIDs.BISMUTH_LVL_3: "Launches homing missile towards target.\nMissile capable of hitting 3 creeps before being destroyed.\nAfter every hit, missile damage is reduced by 10.\nMissile will target new creep after hit if one is in range.\n",
    TowerConstants.TowerIDs.BISMUTH_LVL_4: "Launches one homing missile towards target, and another in the opposite direction.\nMissiles a have 30% chance of stunning creep for 1.5 seconds.",
    TowerConstants.TowerIDs.BISMUTH_LVL_5: "Launches one homing missile towards target, and another in the opposite direction.\nMissiles a have 40% chance of stunning creep for 1.0 seconds.",
    TowerConstants.TowerIDs.LARIMAR_LVL_1: "Fires bullet towards creep.\nBullet reduces creep speed by 10% for 1.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_2: "Launches homing missile towards creep.\nMissile reduces creep speed by 20% for 1.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_3: "Launches homing missile towards creep.\nMissile reduces all creeps' speed close to it\n by 20% for 2.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_4: "Fires homing bullet towards creep.\nBullet reduces all creeps' speed close to it\n by 20% for 2.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_5: "Launches homing missile towards creep.\nMissile reduces all creeps' speed close to it\n by 25% for 3.0 seconds when hit.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_1: "Fires three bullets in a star formation,\nwith a randomly chosen direction for one projectile\nand the others evenly spaced around it,\ncreating a rotating spread with each shot.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_2: "Fires three bullets in a star formation,\nwith one aimed directly at the target\nand the others evenly spaced around it,\ncreating a consistent spread centered on a creep.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_3: "Fires four bullets in a star formation,\nwith one aimed directly at the target\nand the others evenly spaced around it,\ncreating a consistent spread centered on a creep.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_4: "Launches four in a star formation,\nwith one aimed directly at the target\nand the others evenly spaced around it,\ncreating a consistent spread centered on a creep.\nNon-targeted missiles are capable of retargeting\n whenever they are close by.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_5: "Launches five in a star formation,\nwith one aimed directly at the target\nand the others evenly spaced around it,\ncreating a consistent spread centered on a creep.\nMissilles ricochet in a random direction when they hit a creep.\nMissiles lose 20 damage after first hit.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_1: "Launches missile towards creep.\nMissile capable of hitting two creeps before it is destroyed.\nOnce the missile hits a creep,\nit will ricochet in a random direction.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_2: "Launches missile towards creep.\nMissile capable of hitting three creeps before it is destroyed.\nOnce the missile hits a creep,\nit will ricochet in a random direction.",
    TowerConstants.TowerIDs.SPINEL_LVL_1: "Launches homing missile towards target.\nMissile deals 5 damage to all creeps in\n close proximity when it hits a creep.",
    TowerConstants.TowerIDs.SPINEL_LVL_2: "Launches homing missile towards target.\nMissile deals 15 damage to all creeps in\n close proximity when it hits a creep.",
    TowerConstants.TowerIDs.SPINEL_LVL_3: "Launches homing missile towards target.\nMissile deals 20 damage to all creeps in\n close proximity when it hits a creep.",
    TowerConstants.TowerIDs.SPINEL_LVL_4: "Launches homing missile towards target.\nMissile deals 40 damage to all creeps in\n close proximity when it hits a creep.",
    TowerConstants.TowerIDs.SPINEL_LVL_5: "Launches homing missile towards target.\nMissile deals 120 damage to all creeps in\n close proximity when it hits a creep.",
    TowerConstants.TowerIDs.KUNZITE_LVL_1: "Fires up to two homing missiles at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_2: "Fires up to three bullets at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_3: "Fires up to three homing missiles at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_4: "Fires up to four bullets at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_5: "Simultaneously launches homing missiles at all creeps in range.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_1: "Fires missile in random direction that is\ncapable of targeting nearby creeps",
    TowerConstants.TowerIDs.SAM_SITE_LVL_2: "Fires two missiles in random direction that is\ncapable of targeting nearby creeps",
    TowerConstants.TowerIDs.SAM_SITE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_3: "Launches up to two homing missiles at different creeps a time.\nMissile capable of hitting three creeps before it is destroyed.\nOnce the missile hits a creep,\nit will ricochet in a random direction.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_1: "Burns all creeps that enter tower range,\ndealing 10 damage per second.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_2: "Burns all creeps that enter tower range,\ndealing 20 damage per second.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_3: "Burns all creeps that enter tower range,\ndealing 80 damage per second.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_1: "Slows movement of all creep in range by 20%.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_2: "Slows movement of all creep in range by 30%.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_3: "Slows movement of all creep in range by 35%.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_1: "Stuns a creep in range for 1.5 seconds.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_2: "Stuns a creep in range for 2.0 seconds.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_3: "Stuns two creeps in range for 2.0 seconds.",
}
