extends Node2D

const TOWER_ID_TO_DESCRPTION_TEXT: Dictionary[TowerConstants.TowerIDs, String]  = {
    TowerConstants.TowerIDs.BARRICADE: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BISMUTH_LVL_1: "Fires homing missile towards target.",
    TowerConstants.TowerIDs.BISMUTH_LVL_2: "Fires homing missile towards target.\nMissile has 15% chance of 0.5 seconds stun.",
    TowerConstants.TowerIDs.BISMUTH_LVL_3: "Fires homing missile towards target.\nMissile capable of hitting 3 creeps before being destroyed.\nAfter every hit, missile damage is reduced by 10.\nMissile will target new creep after hit if one is in range.\n",
    TowerConstants.TowerIDs.BISMUTH_LVL_4: "Fires one homing missile towards target, and another in the exact opposite direction.\nMissiles have 30% chance of 1.5 seconds stun.",
    TowerConstants.TowerIDs.BISMUTH_LVL_5: "Fires one homing missile towards target, and another in the exact opposite direction.\nMissiles have 40% chance of 1.0 seconds stun.",
    TowerConstants.TowerIDs.LARIMAR_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LARIMAR_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LARIMAR_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LARIMAR_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LARIMAR_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.KUNZITE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.KUNZITE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.KUNZITE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.KUNZITE_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.KUNZITE_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_3: "Tower descrption found but not given description.",
}
