extends Node2D

const TOWER_ID_TO_DESCRPTION_TEXT: Dictionary[TowerConstants.TowerIDs, String]  = {
    TowerConstants.TowerIDs.BARRICADE: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_1: "Fires bullet towards creep.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_2: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will ricochet in a random direction.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_3: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will travel towards other another\ncreep in range (if one exists).",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_4: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will ricochet in a random direction.",
    TowerConstants.TowerIDs.BLACK_MARBLE_LVL_5: "Fires bullet towards creep.\nBullet capable of hitting two creeps before it is destroyed.\nOnce the bullet hits a creep, it will travel towards other another\ncreep in range (if one exists).",
    TowerConstants.TowerIDs.BISMUTH_LVL_1: "Fires homing missile towards target.",
    TowerConstants.TowerIDs.BISMUTH_LVL_2: "Fires homing missile towards target.\nMissile has 15% chance of 0.5 seconds stun.",
    TowerConstants.TowerIDs.BISMUTH_LVL_3: "Fires homing missile towards target.\nMissile capable of hitting 3 creeps before being destroyed.\nAfter every hit, missile damage is reduced by 10.\nMissile will target new creep after hit if one is in range.\n",
    TowerConstants.TowerIDs.BISMUTH_LVL_4: "Fires one homing missile towards target, and another in the opposite direction.\nMissiles a have 30% chance of stunning creep for 1.5 seconds.",
    TowerConstants.TowerIDs.BISMUTH_LVL_5: "Fires one homing missile towards target, and another in the opposite direction.\nMissiles a have 40% chance of stunning creep for 1.0 seconds.",
    TowerConstants.TowerIDs.LARIMAR_LVL_1: "Fires bullet towards creep.\nBullet reduces creep speed by 10% for 1.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_2: "Fires homing missile towards creep.\nMissile reduces creep speed by 20% for 1.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_3: "Fires homing missile towards creep.\nMissile reduces all creeps' speed close to it\n by 20% for 2.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_4: "Fires homing bullet towards creep.\nBullet reduces all creeps' speed close to it\n by 20% for 2.0 seconds when hit.",
    TowerConstants.TowerIDs.LARIMAR_LVL_5: "Fires homing missile towards creep.\nMissile reduces all creeps' speed close to it\n by 25% for 3.0 seconds when hit.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SUNSTONE_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_4: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SPINEL_LVL_5: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.KUNZITE_LVL_1: "Fires up to two homing missiles at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_2: "Fires up to three bullets at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_3: "Fires up to three homing missiles at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_4: "Fires up to four bullets at different\ncreeps in range simultaneously.",
    TowerConstants.TowerIDs.KUNZITE_LVL_5: "Simultaneously fires homing missiles at all creeps in range.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.SAM_SITE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.TOMBSTONE_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.LAVA_POOL_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.ICE_SHARD_LVL_3: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_1: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_2: "Tower descrption found but not given description.",
    TowerConstants.TowerIDs.EMP_STUNNER_LVL_3: "Tower descrption found but not given description.",
}
